# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #9A9EB7

background #131419 
foreground #C2C6E1

color0 #05050C
color1 #2A2B3B
color2 #47495C
color3 #595C70
color4 #65697E
color5 #72768D
color6 #80839C
color7 #B2B5D0
color8 #757890
color9 #2A2B3B
color10 #47495C
color11 #595C70
color12 #65697E
color13 #72768D
color14 #80839C
color15 #D0D1DF

mark1_foreground #666C9C
mark2_foreground #8E95D0
mark3_foreground #666C9C
