return {
  background = "{{ background | lighten(0.0627) }}",
  foreground = "{{ foreground }}",
  colour0 = "{{ color0 }}",
  colour1 = "{{ color1 | darken(0.5) }}",
  colour2 = "{{ color2 }}",
  colour3 = "{{ color3 }}",
  colour4 = "{{ color4 }}",
  colour5 = "{{ color5 }}",
  colour6 = "{{ color6 }}",
  colour7 = "{{ color7 }}",
  colour8 = "{{ color8 }}",
  colour9 = "{{ color9 }}",
  colour10 = "{{ color10 }}",
  colour11 = "{{ color11 }}",
  colour12 = "{{ color12 }}",
  colour13 = "{{ color13 }}",
  colour14 = "{{ color14 }}",
  colour15 = "{{ color15 }}",
}
